### ISSUE TITLE
Google News Integration

### ISSUE THREAD

**Issue by nicholasprussen** [nicholasprussen/cs354-project#12]
Integrate Google News Timeline into our extension

- [ ] Top stories list
- [ ] For you list, user integration
- [ ] World news list
