### ISSUE TITLE
YouTube Integration

### ISSUE THREAD

**Issue by nicholasprussen** [nicholasprussen/cs354-project#5]
Integrate YouTube into our extension

- [x] Check for allowed embeds
- [x] Fill out iFrame with embedded video
- [x] Search functionality for new videos
- [x] Paste functionality for videos
- [ ] Recommended videos

**Comment by nicholasprussen** [comment]
Added paste link functionality and youtube integration basically done

**Comment by nicholasprussen** [comment]
d3c7beed07c7a6f2df245f5e9489867f2e066e3c
